"""create_initial_schema

Revision ID: 9868dcc28f18
Revises:
Create Date: 2026-03-01 14:57:18.848689

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9868dcc28f18"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "positions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticker", sa.String(length=10), nullable=False),
        sa.Column("strategy_type", sa.Enum("WHEEL", name="strategytype"), nullable=False),
        sa.Column(
            "status", sa.Enum("active", "paused", "closed", name="wheelstatus"), nullable=False
        ),
        sa.Column(
            "phase",
            sa.Enum(
                "CSP_OPEN",
                "CSP_EXPIRED",
                "CSP_CLOSED_PROFIT",
                "CSP_CLOSED_LOSS",
                "HOLDING_SHARES",
                "CC_OPEN",
                "CC_EXPIRED",
                "CC_CLOSED_PROFIT",
                "CC_CLOSED_LOSS",
                "WHEEL_COMPLETE",
                name="wheelphase",
            ),
            nullable=False,
        ),
        sa.Column("opened_date", sa.Date(), server_default=sa.text("CURRENT_DATE"), nullable=False),
        sa.Column("closed_date", sa.Date(), nullable=True),
        sa.Column("account_id", sa.String(length=64), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("thesis", sa.Text(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_positions_status_phase", "positions", ["status", "phase"], unique=False)
    op.create_index("ix_positions_ticker", "positions", ["ticker"], unique=False)
    op.create_table(
        "cost_basis_snapshots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column("basis_per_share", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("total_premium_collected", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("final_pnl", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("annualized_return", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("snapshot_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "legs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("position_id", sa.UUID(), nullable=False),
        sa.Column(
            "leg_role",
            sa.Enum(
                "csp",
                "short_cc",
                "stock_assignment",
                name="legrole",
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum(
                "open",
                "close",
                "expire",
                "assign",
                "exercise",
                "roll_from",
                "roll_to",
                name="legaction",
            ),
            nullable=False,
        ),
        sa.Column(
            "option_type", sa.Enum("put", "call", "stock", name="optiontype"), nullable=False
        ),
        sa.Column("strike", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("expiration", sa.Date(), nullable=False),
        sa.Column("contracts", sa.Integer(), nullable=False),
        sa.Column("premium_per_contract", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("fill_price", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("fill_date", sa.Date(), nullable=False),
        sa.Column("order_id", sa.String(length=128), nullable=True),
        sa.Column("roll_chain_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["positions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_legs_position_id_fill_date",
        "legs",
        ["position_id", "fill_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_legs_position_id_fill_date", table_name="legs")
    op.drop_table("legs")
    op.drop_table("cost_basis_snapshots")
    op.drop_index("ix_positions_ticker", table_name="positions")
    op.drop_index("ix_positions_status_phase", table_name="positions")
    op.drop_table("positions")
    op.execute("DROP TYPE IF EXISTS optiontype")
    op.execute("DROP TYPE IF EXISTS legaction")
    op.execute("DROP TYPE IF EXISTS legrole")
    op.execute("DROP TYPE IF EXISTS wheelphase")
    op.execute("DROP TYPE IF EXISTS wheelstatus")
    op.execute("DROP TYPE IF EXISTS strategytype")
    # ### end Alembic commands ###
